# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.20.1


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
"""
There are two methods:
1). using size and itemsize
size: This attribute gives the number of elements present in the NumPy array.

itemsize: This attribute gives the memory size of one element of NumPy array in bytes.

"""
a.size

print("Size of the array: ", a.size)

a.itemsize
print("Memory size of one array in bytes: ", a.itemsize)

print("Memory size of a numpy array in bytes: ", a.size * a.itemsize)

"""
2)Method 2: Using nbytes attribute of NumPy array.

nbytes: This attribute gives the total bytes consumed by the elements of the NumPy array.

"""

print("Memory size of a NumPy array: ", a.nbytes)

Size of the array:  10
Memory size of one array in bytes:  8
Memory size of a numpy array in bytes:  80
Memory size of a NumPy array:  80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"????

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
a = np.zeros(10)
a[4]= 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
b = np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
"""
Ma solution 
c = np.array([1, 2, 0, 0, 4])
for x in c:
    if x > 0:
        print([x])
[1]
[2]
[4]    
        """
""" meilleure solution nonzero"""

c = np.nonzero([1, 2, 0, 0, 4])
print(c)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
#np.eye identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
#np.random.random

e = np.random.random((3,3))
print(e)

[[0.88618291 0.61692082 0.08533161]
 [0.53023679 0.35365396 0.63581839]
 [0.89346973 0.76264569 0.64640362]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [28]:
# 1st method
f = np.random.random((10, 10))
print(f)
print("min(f) = ", f.min())
print("max(f) = ", f.max())

#2nd method
for func in (f.min, f.max):
    print(func.__name__, "=", func())

[[0.33487799 0.75192409 0.91311079 0.52872268 0.46214078 0.99329606
  0.75378114 0.35935358 0.96590479 0.72525167]
 [0.18504741 0.76132295 0.22564997 0.19673529 0.56079404 0.13578157
  0.87673864 0.73968337 0.97797201 0.58710686]
 [0.95027768 0.49007557 0.51639422 0.26509562 0.57101768 0.05411428
  0.47574764 0.14578057 0.57259445 0.32763826]
 [0.6386857  0.89037621 0.89832087 0.94467915 0.77890808 0.68230632
  0.86907469 0.54119857 0.79326954 0.74095766]
 [0.29220909 0.58691699 0.25105259 0.70545122 0.92736446 0.50134545
  0.64199597 0.80430858 0.62687559 0.92826995]
 [0.76889604 0.36873523 0.66341349 0.75428948 0.85062603 0.03932297
  0.21672395 0.6828918  0.41126961 0.64629196]
 [0.37997377 0.60852488 0.8474753  0.21912233 0.98099165 0.34395237
  0.51846495 0.52844449 0.16557125 0.97012377]
 [0.48396231 0.30837624 0.14364421 0.84900195 0.2986967  0.56375451
  0.65100283 0.79905663 0.00214928 0.40259306]
 [0.43132295 0.95209111 0.5235039  0.08807643 0.95840161 0.11158855
  0.2054782 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
g = np.random.random((3,10))

print(g.mean())

0.5091461266200256


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [30]:
h = np.ones((3, 10))
h[1:-1,1:-1]=0
print(h)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [34]:
"""
numpy.pad(array, pad_width, mode='constant', **kwargs) 

# importing Numpy package
import numpy as np
  
# Creating a 3X3 Numpy matrix
array = np.ones((3, 3))
  
print("Original array")
print(array)
  
print("\n0 on the border and 1 inside the array")
  
# constructing border of 0 around 3D identity matrix
# using np.pad()
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
  
print(array)
"""
b = np.pad(b,pad_width = 1, mode ='constant', constant_values = 0)

print(b)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [3]:
import numpy as np   #?????????????????????????????????????????????????????????? I don't understand the results 

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [4]:
i = np.diag(1 + np.arange(4), k= -1)
print(i)

"""
numpy.diag(v, k=0)
Extract a diagonal or construct a diagonal array.
if you use this function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you are using.
Parameters
varray_like
If v is a 2-D array, return a copy of its k-th diagonal.
If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

kint, optional
Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal,
and k<0 for diagonals below the main diagonal.

x = np.arange(9).reshape((3,3))
x
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
       
np.diag(x)
array([0, 4, 8])
np.diag(x, k=1)
array([1, 5])
np.diag(x, k=-1)
array([3, 7])

np.diag(np.diag(x))
array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

See the more detailed documentation for numpy.diagonal

i = np.diag(2 + np.arange(4), k= -1)
print(i)
[[0 0 0 0 0]
 [2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]]
i = np.diag(2 + np.arange(4), k= -2)
print(i)
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [2 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 5 0 0]]
i = np.diag(np.arange(5), k= -1)
print(i)
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]]
i = np.diag(np.arange(4), k= -1)
print(i)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]]

"""


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [7]:
J = np.zeros((10,10),dtype=int)
J[1::2,::2] = 1
J[::2,1::2] = 1
print(J)

"""
or other method = same result

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


"""

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [9]:
a = np.array((6, 7, 8))


print(np.unravel_index(100,(6,7,8)))

"""
np.unravel_index(index, shape, order='C') order is optional
Converts a flat index or array of flat indice into a tuple of coordinate arrays.

Parameters
indicesarray_like
An integer array whose elements are indices into the flattened version of an array of dimensions shape.
Before version 1.6.0, this function accepted just one index value.

shapetuple of ints
The shape of the array to use for unraveling indices.

Changed in version 1.16.0: Renamed from dims to shape.

order{‘C’, ‘F’}, optional
Determines whether the indices should be viewed as indexing in row-major (C-style) or column-major (Fortran-style) order.

New in version 1.6.0.

Returns
unraveled_coordstuple of ndarray
Each array in the tuple has the same shape as the indices array.

"""

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [10]:
K = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(K)

"""
np.tile(A, reps)
Construct an array by repeating A the number of times given by reps.
"""

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [18]:
L = np.random.random((5,5))
print(L)

print("\n")
Lmax, Lmin = L.max(), L.min()
L= (L-Lmax)/(Lmax-Lmin)
print(L)

print("\n")
#other method

L = (L - np.mean (L)) / (np.std (L))
print(L)

[[0.78843678 0.24080756 0.78708352 0.78761067 0.68281527]
 [0.34007069 0.95204818 0.52629425 0.4038969  0.40589891]
 [0.70232861 0.61089745 0.78962569 0.9123735  0.404611  ]
 [0.49750386 0.97797121 0.11134041 0.58385108 0.1479821 ]
 [0.38223048 0.93991615 0.90754928 0.27321393 0.98454765]]


[[-0.22458686 -0.85173376 -0.22613662 -0.22553292 -0.34554499]
 [-0.73805728 -0.03721851 -0.52479341 -0.66496328 -0.66267057]
 [-0.32319824 -0.42790552 -0.22322531 -0.08265409 -0.66414549]
 [-0.55776425 -0.00753137 -1.         -0.45887912 -0.95803781]
 [-0.68977575 -0.05111215 -0.08817881 -0.81462188  0.        ]]


[[ 0.68029199 -1.35770908  0.67525582  0.67721762  0.28722173]
 [-0.98830154  1.2891715  -0.29527094 -0.75077245 -0.74332197]
 [ 0.3598406   0.01957973  0.68471651  1.14152226 -0.74811491]
 [-0.40241429  1.385644   -1.83952085 -0.08107331 -1.70315888]
 [-0.83140399  1.24402219  1.12356892 -1.23710887  1.41011822]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
#Maarten solution


M = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])
rgba = np.dtype([ ('r', np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

#data type of object with field grades
print(dt['grades'])

#data type of object with field name
print(dt['name'])

x = np.array([('Sarah', (8.0, 7.0)), ('John',(6.0, 7.0))], dtype = dt)
color = np.array([((10), (15), (50), (20))], dtype = rgba)

print(x[1])
print(color)


"""color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
                  """

NameError: name 'dt' is not defined

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [31]:
N = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])

O = np.array([[1, 2], [3, 4], [5, 6]])

print(N.shape, O.shape)

P = N.dot(O)
print(P)

#or other method
print("\n")
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
#Z = np.ones((5,3)) @ np.ones((3,2))

(5, 3) (3, 2)
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [34]:
Q = np.arange(11)

Q[(2 < Q) & (Q <= 7)] *= -1
print(Q)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [35]:
R = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(R)), R))

[ -5. -10.  -9.   7.   9.  -2.   4.   4.  -8. -10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [36]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 5 6 9]
